# Generated by Django 3.1.7 on 2021-07-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210710_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBLBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=255)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('api_calls', models.IntegerField(default=0)),
                ('src_address', models.CharField(default='', max_length=255)),
                ('dst_address', models.CharField(default='', max_length=255)),
                ('format', models.TextField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'TBLBRIDGE',
            },
        ),
    ]
