# Generated by Django 3.1.7 on 2021-07-15 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_tblbridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBLFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'TBLFREQUENCY',
            },
        ),
        migrations.RemoveField(
            model_name='tblbridge',
            name='user_id',
        ),
        migrations.AddField(
            model_name='tblbridge',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tblbridge',
            name='third_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblbridge',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tblbridge',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='tblbridge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tblbridge',
            name='type',
            field=models.IntegerField(choices=[(1, 'ws2wh'), (2, 'wh2ws'), (3, 'ws2api'), (4, 'api2ws')]),
        ),
        migrations.AddField(
            model_name='tblbridge',
            name='frequency',
            field=models.ManyToManyField(to='db.TBLFrequency'),
        ),
    ]
