# Generated by Django 3.1.7 on 2021-07-15 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210715_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblbridge',
            name='frequency',
        ),
        migrations.AddField(
            model_name='tblbridge',
            name='frequency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblbridge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TBLFrequency',
        ),
    ]
