# Generated by Django 3.1.7 on 2021-07-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20210715_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbridge',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
