# Generated by Django 3.1.7 on 2021-07-18 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20210716_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblbridge',
            name='third_response',
        ),
        migrations.CreateModel(
            name='TBLLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=255)),
                ('date_from', models.DateTimeField(auto_now_add=True)),
                ('date_to', models.DateTimeField(auto_now_add=True)),
                ('is_full', models.BooleanField(default=False)),
                ('bridge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.tblbridge')),
            ],
            options={
                'db_table': 'TBLLOG',
            },
        ),
    ]
