# Generated by Django 3.1.7 on 2021-07-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20210718_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbllog',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
