# Generated by Django 3.1.7 on 2021-07-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_tbllog_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TBLSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(default='', max_length=255)),
                ('priv_key_directory', models.CharField(default='', max_length=255)),
                ('cert_directory', models.CharField(default='', max_length=255)),
                ('privacy_link', models.CharField(default='', max_length=255)),
                ('user_link', models.CharField(default='', max_length=255)),
                ('max_active_bridges', models.IntegerField(default=1)),
                ('rate_limit_per_url', models.IntegerField(default=14)),
                ('allowed_frequency', models.TextField(blank=True, null=True)),
                ('available_bridges', models.TextField(blank=True, null=True)),
                ('smtp_server_name', models.CharField(default='', max_length=255)),
                ('smtp_port', models.CharField(default='', max_length=255)),
                ('smtp_authentication', models.BooleanField(default=True)),
                ('smtp_enable_starttls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(default='', max_length=255)),
                ('smtp_password', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'TBLSETTING',
            },
        ),
    ]
