# Generated by Django 3.1.7 on 2021-07-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_tblsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblsetting',
            name='cert_directory',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='max_active_bridges',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='priv_key_directory',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='privacy_link',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='rate_limit_per_url',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='server_name',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='smtp_authentication',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='smtp_enable_starttls',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='smtp_server_name',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='smtp_username',
        ),
        migrations.RemoveField(
            model_name='tblsetting',
            name='user_link',
        ),
        migrations.AddField(
            model_name='tblsetting',
            name='server_setting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblsetting',
            name='smtp_setting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
