# Generated by Django 3.1.7 on 2021-07-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20210722_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsetting',
            name='max_active_bridges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tblsetting',
            name='rate_limit_per_url',
            field=models.IntegerField(default=0),
        ),
    ]
