# Generated by Django 3.1.7 on 2021-07-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0014_remove_tblbridge_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='reset_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
